spring:
  profiles:
    active: local
  application:
    name: spring-logging
  main:
    banner-mode: off

---

spring:
  profiles: local
server:
  email: local@email.com

---

spring:
  profiles: dev
server:
  email: dev@email.com